# Generated by Django 5.2.3 on 2025-06-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="unique_id",
            field=models.CharField(
                blank=True, editable=False, max_length=8, null=True, unique=True
            ),
        ),
    ]
